#!/bin/bash

CURR_DIR=$(pwd)

# Get the branch name being pushed
current_branch=$(git symbolic-ref --short HEAD)

# Check if the branch has been pushed before
if [ $(git rev-parse --verify origin/$current_branch) ]; then
  echo "Branch '$current_branch' has already been pushed to remote. Skipping hook."
  exit 0
fi

# Run your Git hook commands here
echo "Running Git hook commands for branch '$current_branch'..."

"$CURR_DIR"/suggestion.sh
