#!/bin/bash

CURR_DIR=$(pwd)

# Set the file name based on the operating system
if [[ "$OSTYPE" == "darwin"* ]]; then
  # For macOS
  export FILE_PATH=/tmp/myfile.txt
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
  # For Linux
  export FILE_PATH=/tmp/myfile_linux.txt
elif [[ "$OSTYPE" == "cygwin" ]]; then
  # For Windows using Cygwin
  export FILE_PATH=/tmp/myfile_windows.txt
else
  echo "Unsupported operating system."
  exit 1
fi